# Generated by Django 4.2.9 on 2024-03-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gitrepodetail_dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('repositories', models.CharField(max_length=100)),
                ('stars_count', models.IntegerField()),
                ('forks_count', models.IntegerField()),
                ('pull_requests', models.IntegerField()),
                ('contributors', models.IntegerField()),
                ('language', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=100)),
                ('topics', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'gitrepodetail_dataset',
            },
        ),
        migrations.CreateModel(
            name='gitreponame_dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('repositories', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gitreponame_dataset',
            },
        ),
        migrations.CreateModel(
            name='gitusername_dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('gitusername', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gitusername_dataset',
            },
        ),
    ]
