# Generated by Django 4.2.9 on 2024-07-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_gituserall_dataset_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('webdev', 'Web Development'), ('ml', 'Machine Learning'), ('uiux', 'UI/UX Development'), ('iot', 'Internet of Things'), ('blockchain', 'Blockchain Technology'), ('cybersec', 'Cybersecurity'), ('cloud', 'Cloud Computing')], max_length=50),
        ),
    ]
